### ISSUE TITLE
osinstancectl doesn't use the template provided in /srv/openslides/OpenSlides

### ISSUE THREAD

**Issue by convernaticspeter** [OpenSlides/openslides-docker-compose#10]
Hi there,

I am currently trying to change the looks of my OS clients that are populated by osinstancectl. Unfortnately osinstancectl ignores changes, that I make to the template in the template directory defined in osinstancectl.sh.

Here is how I thought I have to do it:
1) remove the current instance with the name
2) change the necessary files in /srv/openslides/OpenSlides/client
3) add the instance
4) enjoy the changed colors/logos

What did I miss? Is the tool ignoring the template dir? If so, where to make the changes?

**Comment by convernaticspeter** [comment]
I also tried rebuilding the images - didn't work.

**Comment by gsiv** [comment]
> Unfortnately osinstancectl ignores changes, that I make to the template in the template directory defined in osinstancectl.sh.

I'm afraid you are reading too much into osinstancectl's `TEMPLATE_REPO` variable.  `TEMPLATE_REPO` is the directory from which osinstancectl takes its YAML and `.env` configuration templates.  In other words, it's a template for what defines an OpenSlides instance.  That's it.

osinstancectl starts containers based on existing images.  It does not rebuild them.

> I also tried rebuilding the images - didn't work.

Good, here you are on the right track.  If you can build the images prior to making your changes but run into those NPM errors afterwards, then there is your problem.  You should probably read the error messages carefully and investigate the log files mentioned in them.

I'm closing this issue because I believe that it has nothing to do with osinstancectl.  Feel free to open another issue if you think that something might be wrong with the build script, the client image etc.
