### ISSUE TITLE
SAML integration in Docker installation

### ISSUE THREAD

**Issue by topelrapha** [OpenSlides/openslides-docker-compose#6]
Hey,

is there a smooth way to enable SAML in Docker installation?
I found the config property in settings.py but there is a missing python module which is not in the production or big mode regiuirements file.

Do you have any idea?

Thanks in advance!

**Comment by tsiegleauq** [comment]
As far as I remember "OpenSlides for SAML" is a little bit special. I think @FinnStutzenstein can elaborate on that.

**Comment by topelrapha** [comment]
Thanks for your reply.. I will create a pull request with a working proposal the next days

**Comment by FinnStutzenstein** [comment]
Hi, I'm not sure why I didn't get a notification about this issue, sorry!

> is there a smooth way to enable SAML in Docker installation?

All prerequisits (xmlsec ..) are installed (https://github.com/OpenSlides/openslides-docker-compose/blob/master/server/Dockerfile#L42) just the `python3-saml` package is missing.

I do not know how we do this on our productive instances. I think you can create a fork of OpenSlides, add `python3-saml` into the `requeirements/production.txt` and use your fork to build the image. This is not great, but should work.

@gsiv @emanuelschuetze How do you manage this on all productive saml instances?

We do not include `python3-saml` per default, because it is an unnecessary extra dependency for most people. But I also see, that this way is not great.

@gsiv Is it possible to add a build arg "SAML=true|false" that, if enabled, executes `pip install python3-saml`? So one can dynamically enable SAML at build time without having to make special forks/branches.

**Comment by topelrapha** [comment]
> @gsiv Is it possible to add a build arg "SAML=true|false" that, if enabled, executes pip install python3-saml? So one can dynamically enable SAML at build time without having to make special forks/branches.

This is the way I would prefer and would be part of my propsal. Maybe we create a .env file for all configuration options. Unfortunately in current configuration you have to change the git repo url in two different files. This isn't very comfortable.

Thanks for your work!

**Comment by topelrapha** [comment]
obsolete
